name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install . pytest black isort mypy
      - run: pytest
      - run: black --check src tests
      - run: isort --check-only src tests
      - run: mypy src
